name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependancies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pytest
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest